stages:
    - build
    - test
    - deploy

test tac:
    stage: test
    tags:
         - ruby-1
    script:
        - rspec
variables:
    RUBY_VERSION: '2.7'
    
build tac:
    stage: build
    tags:
        - ruby-1
    script:
        - bundle install 

deploy tac:
    stage: deploy
    tags:
        - ruby-1
    script:
        - echo "Deploying Tic-Tac-Toe game"
