stages:
    - build
    - test
    - deploy

test tac:
    stage: test
    tags:
         - ruby-1
    script:
        - rspec spec/cell_spec
variables:
    RUBY_VERSION: '2.7'
    
build tac:
    stage: build
    tags:
        - ruby-1
    script:
        - bundle gem tic_tac_toe

deploy tac:
    stage: deploy
    tags:
        - ruby-1
    script:
        - "Deploying Tic Tac Toe"


