stages:
    - build
    - test
    - deploy

test tac:
    stage: test
    tags:
         - tic
    script:
        - rspec spec/cell_spec.rb
variables:
    RUBY_VERSION: '2.7'
    
build tac:
    stage: build
    tags:
        - tic
    script:
        - bundle gem tic_tac_toe

deploy tac:
    stage: deploy
    tags:
        - tic
    script:
        - echo "Deploying Tic-Tac-Toe game"


